# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975cdf170232925dbaec036c762d2ecaebcff97602f7738530c6edb5924618515782ae4d1df2eb80a8f5957cab28635e7e7eeb0fb88867fb1bd0058f0c62fd4c

test:
  secret_key_base: aa343481da05607c19b09b4fc2f75214c003b6e7a4e03fe3819de06fc40ea931e2e02f729b59d3cdd931535b0ebcb342db08f89b0b232c10dad9b47603e5d04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
